### ISSUE TITLE
Error in strptime function

### ISSUE THREAD

**Issue by warbringer** [robinostlund/volkswagencarnet#1]
Currently using the latest version of volkswagencarnet custom component for home assistant 0.62.1 and volkswagencarnet (2.0.21) python module.

Got this error when starting it up:
```
Feb 22 22:54:08 hassbian hass[12792]: Traceback (most recent call last):
Feb 22 22:54:08 hassbian hass[12792]: File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
Feb 22 22:54:08 hassbian hass[12792]: result = next(coro)
Feb 22 22:54:08 hassbian hass[12792]: File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 429, in _async_add_entity
Feb 22 22:54:08 hassbian hass[12792]: yield from entity.async_update_ha_state()
Feb 22 22:54:08 hassbian hass[12792]: File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 212, in async_update_ha_state
Feb 22 22:54:08 hassbian hass[12792]: state = self.state
Feb 22 22:54:08 hassbian hass[12792]: File "/home/homeassistant/.homeassistant/custom_components/sensor/volkswagen_carnet.py", line 25, in state
Feb 22 22:54:08 hassbian hass[12792]: val = getattr(self.vehicle, self._attribute)
Feb 22 22:54:08 hassbian hass[12792]: File "/srv/homeassistant/lib/python3.4/site-packages/volkswagencarnet.py", line 346, in last_connected
Feb 22 22:54:08 hassbian hass[12792]: return datetime.strptime(last_connected, '%d.%m.%Y%H:%M').strftime("%Y-%m-%d %H:%M:%S")
Feb 22 22:54:08 hassbian hass[12792]: File "/usr/lib/python3.4/_strptime.py", line 500, in _strptime_datetime
Feb 22 22:54:08 hassbian hass[12792]: tt, fraction = _strptime(data_string, format)
Feb 22 22:54:08 hassbian hass[12792]: File "/usr/lib/python3.4/_strptime.py", line 337, in _strptime
Feb 22 22:54:08 hassbian hass[12792]: (data_string, format))
Feb 22 22:54:08 hassbian hass[12792]: ValueError: time data '22-02-201819:05' does not match format '%d.%m.%Y%H:%M'

```
I went ahead and changed the following in volkswagencarnet.py, on line 346:
`return datetime.strptime(last_connected, '%d.%m.%Y%H:%M').strftime("%Y-%m-%d %H:%M:%S")`
to
`return datetime.strptime(last_connected, '%d-%m-%Y%H:%M').strftime("%Y-%m-%d %H:%M:%S")`
in /srv/homeassistant/lib/python3.4/site-packages/volkswagencarnet.py and I don't get an error anymore. Everything else seems to be working fine.

**Comment by robinostlund** [comment]
Solved :) thanks for output.
