### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Konstigt** [robinostlund/volkswagencarnet#11]
I get this repeatedly on my new VW GTE. Component is fully updated. It seems to work after I restart Home Assistant for a while.

HA 0.103.5.

```
2020-01-02 10:42:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/home/homeassistant/homeassistant/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 200, in state_attributes
    self.target_temperature,
  File "/home/homeassistant/.homeassistant/custom_components/volkswagencarnet/climate.py", line 54, in target_temperature
    return float(self.instrument.target_temperature)
TypeError: float() argument must be a string or a number, not 'NoneType'

```

**Comment by Konstigt** [comment]
Oops, wrong repository.
