### ISSUE TITLE
raise without exception

### ISSUE THREAD

**Issue by milkboy** [robinostlund/volkswagencarnet#144]
When using this component, warnings like this might show up

```
exceptions must derive from BaseException
Traceback (most recent call last):
  File "<SNIP>/venv/lib/python3.9/site-packages/vw_connection.py", line 304, in _login
    raise Exception('User appears unauthorized')
Exception: User appears unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<SNIP>/venv/lib/python3.9/site-packages/vw_connection.py", line 322, in _login
    raise error
TypeError: exceptions must derive from BaseException
```
from
```
error = parse_qs(urlparse(ref).query).get('error', '')[0]
<snip>
raise error
```

Should replace with an Exception

**Comment by milkboy** [comment]
```
 $ pip uninstall volkswagencarnet
Found existing installation: volkswagencarnet 4.4.38
Uninstalling volkswagencarnet-4.4.38:
  Would remove:
    <snip>/lib/python3.9/site-packages/*
  Would not remove (might be manually added):
^C
```
