### ISSUE TITLE
Updates stopped

### ISSUE THREAD

**Issue by OZ1SEJ** [robinostlund/volkswagencarnet#256]
All entities stopped updating a few days ago. I'm on version 4.5.9. You should have credentials... :-)

![billede](https://github.com/robinostlund/volkswagencarnet/assets/2393164/10412b79-c945-4d43-9374-9e16c652cd8a)

**Comment by OZ1SEJ** [comment]
Update: I checked the log, which was flooded with these:
```
ValueError: Instrument not found; component: device_tracker, attribute: position
2024-04-04 05:58:03.854 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/volkswagencarnet/__init__.py", line 288, in async_write_ha_state
    backend_refresh_time = self.instrument.last_refresh
                           ^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagencarnet/__init__.py", line 337, in instrument
    return self.data.instrument(self.vin, self.component, self.attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/volkswagencarnet/__init__.py", line 241, in instrument
    raise ValueError(f"Instrument not found; com
ponent: {component}, attribute: {attr}")```
I restarted HA, and everything works again... :-)
