### ISSUE TITLE
Type error in vw_utilities

### ISSUE THREAD

**Issue by pahenning** [robinostlund/volkswagencarnet#259]
Hi, probably wrong package, but need to mention it anyhow:

Traceback (most recent call last):
  File "/root/carnet.py", line 2, in <module>
    from volkswagencarnet.vw_connection import Connection
  File "/usr/local/lib/python3.9/dist-packages/volkswagencarnet/vw_connection.py", line 36, in <module>
    from .vw_utilities import json_loads
  File "/usr/local/lib/python3.9/dist-packages/volkswagencarnet/vw_utilities.py", line 26, in <module>
    def find_path_in_dict(src: dict | list, path: str | list) -> object:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Regards

pah

**Comment by stickpin** [comment]
Hi @pahenning,

You need to update your python. 
As this library is mostly built to be used by Home Assistant integration, I would suggest you go all the way to v3.12.x.

BR.

**Comment by pahenning** [comment]
Hmmm. Upgraded to Python3.12.1, fine. But installation of volkswagencarnet still fails, because gcc crashes(!) when trying to install lxml (which is needed)
